# Add dank git aliases
git config --global alias.yoink           'fetch'
git config --global alias.plop            'push'
git config --global alias.yolo-plop       'push -f'
git config --global alias.cheeky-peek     'show'
git config --global alias.wibble          'checkout'
git config --global alias.wobble          'branch'
git config --global alias.wibble-wobble   'checkout -b'
git config --global alias.swiggity        'pull'
git config --global alias.swooty          'rebase'
git config --global alias.swiggity-swooty 'pull --rebase'
git config --global alias.time-cube       'log --pretty oneline -n 20 --graph --abbrev-commit'
git config --global alias.booty           'stash'
git config --global alias.uwot            'amend --reuse-message HEAD'
git config --global alias.baby            'init'
git config --global alias.notice          'add'
git config --global alias.senpai          'commit'
git config --global alias.spoon           'clone'
git config --global alias.fam             'status'
git config --global alias.yeah-nah        'pull --ff-only'
